name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Check if 'client' directory exists
        id: check_client_dir
        run: |
          if [ -d "client" ]; then
            echo "client directory exists"
            echo "CLIENT_DIR_EXISTS=true" >> $GITHUB_ENV
          else
            echo "client directory does not exist"
            echo "CLIENT_DIR_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Set up Node.js 20
        if: env.CLIENT_DIR_EXISTS == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        if: env.CLIENT_DIR_EXISTS == 'true'
        run: |
          cd client
          npm install

      - name: Build the application
        if: env.CLIENT_DIR_EXISTS == 'true'
        run: |
          cd client
          CI=false npm run build

      - name: List files in build directory
        if: env.CLIENT_DIR_EXISTS == 'true'
        run: |
          ls -la client/build

      - name: Check for index.html in build directory
        if: env.CLIENT_DIR_EXISTS == 'true'
        run: |
          if [ -f "client/build/index.html" ]; then
            echo "index.html found in build directory"
          else
            echo "index.html not found in build directory"
            exit 1
          fi

      - name: Build And Deploy
        if: env.CLIENT_DIR_EXISTS == 'true'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_052797310 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "./client" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "./client/build" # Built app content directory
          skip_app_build: true
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_052797310 }}
          action: "close"
